### ISSUE TITLE
Spam - Heri Sample Assets – Water, debris, and chess set.

### ISSUE THREAD

**Issue by kernjackson** [matiascodesal/awesome-usd#7]
The following link leads to a scam site [Heri Sample Assets](https://heri.blog/category/freescenes/) – Water, debris, and chess set.

![scam-bot](https://github.com/user-attachments/assets/357cf445-6ad4-4bed-9c4a-b96196c2f8a3)

**Comment by matiascodesal** [comment]
Thank you @kernjackson! The domain must have been abandoned by the original author. I've removed it now.
